<?php 
    $user = $dados[0];
?>
<section class="mt-3 card card-body">
    <h1>Editar Usuário</h1>

    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="name">Nome</label>
                <input name="name" type="text" id="name" class="form-control mb-3" value="<?php echo $user->name; ?>">

                <label for="email">Email</label>
                <input name="email" type="text" id="email" class="form-control mb-3" value="<?php echo $user->email; ?>">

                <label for="password">Senha</label>
                <input name="password" type="text" id="password" class="form-control mb-3">

                <label for="profile">Perfil</label>
                <select name="profile" id="profile" class="form-select mb-3" value="<?php echo $user->profile; ?>">
                    <option value="normal">Normal</option>
                    <option value="admin">Administrador</option>
                </select>

                <button class="btn btn-primary">Pronto</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</section>